networks:
  reflected:

services:
  nginx:
    image: 2345/nginx
    container_name: 2345-nginx
    build: frontend
    ports:
      - "2345:80"
    restart: always
    env_file:
      - .env
    depends_on:
      - django

  django:
    image: 2345/django
    container_name: 2345-django
    build: backend/django
    ports:
      - "2344:8000"
    restart: always
    env_file:
      - .env
    networks:
      - reflected
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: 2345-postgres
    restart: always
    volumes:
      - "reflected_db:/var/lib/postgresql/data"
    expose:
      - "5432"
    env_file:
      - .env
    networks:
      - reflected
volumes:
  reflected_db:
    name: reflected_db
