version: "3.8"

networks:
  transcendence:
services:
  django:
    image: 2345/django
    container_name: 2345-django
    build: backend/django
    ports:
      - "8000:8000"
    restart: always
    networks:
      - transcendence
    # depends_on:
    #   - postgres
  # postgres:
  #   image: postgres:16
  #   container_name: 2345-postgres
  #   restart: always
  #   volumes:
  #     - ts_db:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   env_file:
  #     - .env
  #   networks:
  #     - transcendence
volumes:
  ts_db:
    name: ts_db
